apiVersion: v1
data:
  .dockerconfigjson: '{{ template "imagePullSecret" . }}'
kind: Secret
metadata:
  name: pivotal-registry
  namespace: pivotal-rabbitmq-system
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-cluster-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-operator
  namespace: pivotal-rabbitmq-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq-cluster-operator
        app.kubernetes.io/name: rabbitmq-cluster-operator
        app.kubernetes.io/part-of: rabbitmq
    spec:
      containers:
      - args:
        - --metrics-addr=0
        command:
        - /manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.leaseDuration }}
        - name: LEASE_DURATION
          value: {{ .Values.leaseDuration | quote }}
        {{- end }}
        {{- if .Values.retryPeriod }}
        - name: RETRY_PERIOD
          value: {{ .Values.retryPeriod | quote }}
        {{- end }}
        {{- if .Values.renewDeadline }}
        - name: RENEW_DEADLINE
          value: {{ .Values.renewDeadline | quote }}
        {{- end }}
        image: '{{printf "%s:%s" .Values.images.operator.name .Values.images.operator.tag}}'
        name: operator
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
      imagePullSecrets:
      - name: pivotal-registry
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccountName: rabbitmq-cluster-operator
      terminationGracePeriodSeconds: 10
