apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-cluster-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator-pre-delete
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-operator-pre-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rabbitmq-cluster-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator-pre-delete
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-operator-pre-delete
rules:
- apiGroups:
  - rabbitmq.com
  resources:
  - clusters
  verbs:
  - delete
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-cluster-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator-pre-delete
    app.kubernetes.io/part-of: rabbitmq
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  name: rabbitmq-cluster-operator-pre-delete-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbitmq-cluster-operator-pre-delete
subjects:
- kind: ServiceAccount
  name: rabbitmq-cluster-operator-pre-delete
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-cluster-operator-pre-delete
  labels:
    app.kubernetes.io/component: rabbitmq-cluster-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator-pre-delete
    app.kubernetes.io/part-of: rabbitmq
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: rabbitmq-cluster-operator-pre-delete
      restartPolicy: OnFailure
      containers:
      - name: pre-delete-job
        image: "bitnami/kubectl:latest"
        command: ["kubectl", "delete", "clusters", "--all", "--all-namespaces", "--wait"]
