apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rabbitmq
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-rc-management
        imagePullPolicy: Always
        # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          exec:
            command:
              - "rabbitmq-diagnostics"
              - "ping"
        # https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-liveness-or-readiness-probes
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          exec:
            command:
              - "rabbitmq-diagnostics"
              - "check_running"
        ports:
        - containerPort: 15672
          name: http
        - containerPort: 5672
          name: amqp
        volumeMounts:
        - name: config-volume
          mountPath: /etc/rabbitmq/enabled_plugins
          subPath: enabled_plugins
      volumes:
      - name: config-volume
        configMap:
          name: rabbitmq
          items:
          - key: enabled_plugins
            path: enabled_plugins
