apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
  labels:
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/component: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
- kind: ServiceAccount
  name: rabbitmq-cluster-operator
  namespace: pivotal-rabbitmq-system
