---
name: rabbitmq-cluster-operator
createdAt: '2025-05-02T09:11:31'
image: quay.io/rabbitmqoperator/cluster-operator:2.14.0
version: 2.14.0
replaces: rabbitmq-cluster-operator.v2.13.0
#! See https://access.redhat.com/support/policy/updates/openshift#dates for the list of supported OpenShift versions
supported_openshift_versions: ["4.17", "4.18", "4.19"]