---
# CC, default assumes bosh-lite is used
cc_endpoint: http://127.0.0.1:8181
service:
  username: "p1-rabbit"
  password: "p1-rabbit-testpwd"
  name: "p-rabbitmq"
  offering_description: "this is a description"
  uuid: 00000000-0000-0000-0000-000000000000
  display_name: "WhiteRabbitMQ"
  plan_uuid: 11111111-1111-1111-1111-111111111111
  long_description: "this is a long description"
  provider_display_name: SomeCompany
  documentation_url: https://example.com
  support_url: https://support.example.com
  icon_image: image_icon_base64
  shareable: false
logging:
  level: debug
  print_stack_traces: true
rabbitmq:
  regular_user_tags: "policymaker,management"
  management_domain: pivotal-rabbitmq.127.0.0.1
  hosts:
    - 127.0.0.1
    - 127.0.0.2
  dns_host:
  management:
    username: admin
  administrator:
    username: guest
    password: guest
  operator_set_policy:
    enabled: true
    policy_name: operator_set_policy
    policy_definition: '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
    policy_priority: 50
