---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqclusters.rabbitmq.pivotal.io
  labels:
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/component: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: pivotal-rabbitmq
