# RabbitMQ Cluster Operator
#
# Copyright 2020 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Mozilla Public license, Version 2.0 (the "License").  You may not use this product except in compliance with the Mozilla Public License.
#
# This product may include a number of subcomponents with separate copyright notices and license terms. Your use of these subcomponents is subject to the terms and conditions of the subcomponent's license, as noted in the LICENSE file.
#

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/rabbitmq.com_rabbitmqclusters.yaml
# +kubebuilder:scaffold:kustomizeresource

patches:
- patches/crd_labels_patch.yaml
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_rabbitmqcluster.yaml
# +kubebuilder:scaffold:kustomizepatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
