# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/rabbitmq.pivotal.io_rabbitmqclusters.yaml
# +kubebuilder:scaffold:kustomizeresource

patches:
- patches/crd_labels_patch.yaml
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_rabbitmqclusters.yaml
# +kubebuilder:scaffold:kustomizepatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
