# RabbitMQ Cluster Operator
#
# Copyright 2020 VMware, Inc. All Rights Reserved.
#
# This product is licensed to you under the Mozilla Public license, Version 2.0 (the "License").  You may not use this product except in compliance with the Mozilla Public License.
#
# This product may include a number of subcomponents with separate copyright notices and license terms. Your use of these subcomponents is subject to the terms and conditions of the subcomponent's license, as noted in the LICENSE file.
#

name: rabbitmq
description: RabbitMQ Cluster
apiVersion: v2
version: 0.9.0
appVersion: 3.8.9
keywords:
  - rabbitmq
  - message queue
  - AMQP
home: https://www.rabbitmq.com
icon: https://www.rabbitmq.com/img/rabbitmq_logo_strap.png
engine: gotpl
