name: Release Kubectl to Krew
on:
  release:
    types:
    - published

jobs:
  kubectl_rabbitmq:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update new version in krew-index
      uses: rajatjindal/krew-release-bot@v0.0.46
      with:
        krew_template_file: hack/rabbitmq.yaml
