name: "Update Latest API Reference Wiki page"

on:
  push:
    branches: [ main ]

jobs:
  update-api-reference:
    name: Update Latest API Reference Wiki
    runs-on: ubuntu-latest

    steps:
      - name: Checkout operator codebase
        uses: actions/checkout@v4
        with:
          path: cluster-operator
      - name: Checkout wiki codebase
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: Push to wiki
        run: |
          cd wiki
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          # Update the latest API Reference Doc
          cp ../cluster-operator/docs/api/rabbitmq.com.ref.asciidoc ./API_Reference.asciidoc
          git add ./API_Reference.asciidoc
          git diff-index --quiet HEAD || git commit -m "Update Latest API Reference" && git push
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,action,eventName
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
